parameters:
    
    
services:
    sandbox.listener.presta_sitemap:
        class: Sandbox\SitemapBundle\EventListener\PrestaSitemapListener
        arguments: [@service_container]
        tags: [ {name: "presta.sitemap.listener"} ]
